## Abrar's message

Nash_PCS_calculation.csv: This file includes PCS counts of the genome wide sequences (hg19/mm10) generated by Nash's 1st script 
get_identical_seq_locations

PCS_whole_genome.py: This script calculates PCS lengths of the whole genome and locates their coordinates saving the data as an output TSV format.

PCS_individual_chrom.py: This script calculates PCS lengths of the individual chromosome and locates their coordinates saving the data as an output TSV format.

PCS_hg19mm10_PNAS2006.csv: It contains PCS counts of the genome wide sequences (hg19/mm10) generated by Abrar's Python script. It follows the criteria maintained by PNAS 2006 paper. That is to exlude all smallcases (a, t, c, g, m, x,...etc) and any letters other than [A, T, C, G] like (M, X, V, Y, ..., etc).

PCS_hg19mm10_small_to_upper.csv: It contains PCS counts of the genome wide sequences (hg19/mm10) generated by Abrar's Python script. It contains only the [a, t, c, g, A, T, C, G] similarities. This script converts all the lowercase to uppercase first and then compares if it is in [A, T, C, G] or not. It excludes other letters (B, X, W, M, etc.) except A, T, C, G. This method was also used by Nash et al.

**Note**: Similar files exist for Human/Dog.

PCS_All_files_alltypes_small_to_upper.py: generates "PCS_species_alltypes_small_to_upper.csv"
PCS_All_files_small_to_upper.py: generates "PCS_species_small_to_upper.csv"
PCS_All_files_PNAS2006.py: generates "PCS_species_PNAS2006.csv"


Nash_PCS_calculation.py: This script combines all the TSV files produced by the Nash's 1st script named "get_identical_seq_locations.R". These TSV files are the Nash's version of PCS but there are total of 364 individual TSV files. To get the total PCS counts, Abrar's Python script named "Nash_PCS_calculation.py" combined them all and counted the total PCS distribution to the file named "Nash_PCS_calculation.csv".

*****************************
Please create PCS/species1-species2/ before running "/bucket/.mabuya/MillerU/Abrar/PCS/PCS_whole_genome.py" script